name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Chromedriver
      run: |
        npm install chromedriver
        echo "node_modules/.bin" >> $GITHUB_PATH
    - name: Start Chromedriver
      run: chromedriver --url-base=/wd/hub --port=9515 &
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Start backend
      run: cargo run -- --test &
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose